name: Go Green Schedule 🌳

on:
  schedule:
    - cron: "0 23,7,15 * * *"

jobs:
  go-green-schedule:
    runs-on: ubuntu-latest

    env:
      LIMIT: ${{ secrets.LIMIT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --global user.name 'fazaimron27'
          git config --global user.email 'cincaumyself@gmail.com'
          git config --global --add safe.directory /__w/go-green/go-green

      - name: Loop and commit
        run: |
          for i in $(seq $LIMIT); do
            cat > LAST_UPDATED
            d=$i+`date '+%Y-%m-%dT%H:%M:%SZ'`
            echo $d > LAST_UPDATED
            git add LAST_UPDATED

            commit_message="BOT: DingDong 🔔 has done reforesting 🌳"
            git commit -m "$commit_message"
          done

      - name: Push changes
        run: git push origin main
